#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf ic.params         \
                            output            \
                            render3D.params_0 \
                            render3D.params_1 \
 )
