#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -f                \
    histogram.png                         \
    param_double_boxsize                  \
    param_half_gridsize                   \
    powerspec_snapshot                    \
    powerspec_snapshot_double_boxsize     \
    powerspec_snapshot_half_gridsize      \
    powerspec_snapshot_original           \
    powerspec_snapshot.png                \
    powerspec_snapshot_double_boxsize.png \
    powerspec_snapshot_half_gridsize.png  \
    powerspec_snapshot_original.png       \
    snapshot.hdf5                         \
    snapshot_double_boxsize.hdf5          \
)
