#!/usr/bin/env bash

# This script performs a test of the power spectrum functionality.
# It compares the rms density variation with an estimate obtained by
# taking the rms of cubes the size of spheres with radius
# powerspec_options['tophat']. It also checks the scaling behaviour
# of power spectra (both axes, that is, both k and power) against the
# boxsize and the gridsize of the grid used to compute
# the power spectra.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "$(dirname "${this_dir}")")"

# Set up error trapping
ctrl_c() {
    trap : 0
    exit 2
}
abort() {
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Generate snapshots
"${concept}"                              \
    -n 1                                  \
    -p "${this_dir}/param"                \
    -m "${this_dir}/generate_snapshot.py" \
    --pure-python

# Compute power spectrum of the first snapshot
"${concept}"                                 \
    -n 1                                     \
    -p "${this_dir}/param"                   \
    -u powerspec "${this_dir}/snapshot.hdf5"

# Compute power spectrum of the snapshot with double the boxsize
"${concept}"                                                \
    -n 1                                                    \
    -p "${this_dir}/param"                                  \
    -u powerspec "${this_dir}/snapshot_double_boxsize.hdf5"

# Compute power spectrum of the first snapshot using half the gridsize
mv "${this_dir}/powerspec_snapshot"     "${this_dir}/powerspec_snapshot_original"
mv "${this_dir}/powerspec_snapshot.png" "${this_dir}/powerspec_snapshot_original.png"
"${concept}"                                 \
    -n 1                                     \
    -p "${this_dir}/param"                   \
    -c "_gridsize //= 2"                     \
    -u powerspec "${this_dir}/snapshot.hdf5"
mv "${this_dir}/powerspec_snapshot"              "${this_dir}/powerspec_snapshot_half_gridsize"
mv "${this_dir}/powerspec_snapshot.png"          "${this_dir}/powerspec_snapshot_half_gridsize.png"
mv "${this_dir}/powerspec_snapshot_original"     "${this_dir}/powerspec_snapshot"
mv "${this_dir}/powerspec_snapshot_original.png" "${this_dir}/powerspec_snapshot.png"

# Analyse the output snapshots
"${concept}"                    \
    -n 1                        \
    -p "${this_dir}/param"      \
    -m "${this_dir}/analyze.py" \
    --pure-python

# Test ran successfully. Deactivate traps.
trap : 0
