#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015-2016 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The auther of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This script runs the same, random initial conditions in both compiled
# and pure Python mode and compares the results. The PP algorithm is used.

# Number of processes to use
nprocs_list="1 2 4"

# Scale factor values at which to dump output (Python syntax)
output_times="0.1, 0.5, 1"

# Initialize test environment
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source "${this_dir}/../environment"

# Cleanup from last test run
"${this_dir}/clean"

# Create list of output times
"${python}" -c "import numpy as np; np.savetxt('${this_dir}' + '/outputlist', (${output_times}))"

# Create the Ewald grid using Cython, if it does not already exist
# (for fast IC generation).
ewald_gridsize=$(grep -o "ewald_gridsize[ =0-9]*" "${this_dir}/params" | awk '{printf $NF}')
if [ ! -f "${concept_dir}/.ewald_gridsize=${ewald_gridsize}.hdf5" ]; then
    "${concept}" -n 1 -p "${this_dir}/params_ewald" --local
fi

# Generate ICs
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/generate_IC.py" --pure-python --local

# Run the CO𝘕CEPT code on the generated ICs
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/params" --local
    rm -rf "${this_dir}/output_cython_${n}"
    mv "${this_dir}/output" "${this_dir}/output_cython_${n}"
done

# Run the CO𝘕CEPT code in pure Python mode on the generated ICs
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/params" --pure-python --local
    rm -rf "${this_dir}/output_python_${n}"
    mv "${this_dir}/output" "${this_dir}/output_python_${n}"
done

# Tabulate a small grid using both Cython and pure Python
ewald_gridsize_small=$(grep -o "ewald_gridsize[ =0-9]*" "${this_dir}/params_ewald_small" | awk '{printf $NF}')
rm -f "${concept_dir}/.ewald_gridsize=${ewald_gridsize_small}.hdf5"
"${concept}" -n 1 -p "${this_dir}/params_ewald_small" --local
mv "${concept_dir}/.ewald_gridsize=${ewald_gridsize_small}.hdf5" "${this_dir}/ewald_cython.hdf5"
"${concept}" -n 1 -p "${this_dir}/params_ewald_small" --pure-python --local
mv "${concept_dir}/.ewald_gridsize=${ewald_gridsize_small}.hdf5" "${this_dir}/ewald_python.hdf5"

# Analyze the output snapshots and Ewald grids
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Finalize test environment
test_done=true source "${this_dir}/../environment"

