#!/usr/bin/env bash

# This script runs the same, random initial conditions in both compiled
# and pure Python mode and compares the results. The PP algorithm is used.

# Number of processes to use
nprocs_list=(1 2 4)

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Create the Ewald grid using Cython
ewald_gridsize="$(get_param ewald_gridsize)"
echo "ewald_gridsize = ${ewald_gridsize}" > "${this_dir}/params_ewald"
"${concept}" -n 1                                \
             -p "${this_dir}/params_ewald"       \
             -m "import ewald; ewald.tabulate()" \
             --local

# Generate ICs
echo "$(cat "${this_dir}/params")
output_dirs  = {'snapshot': '${this_dir}'}
output_bases = {'snapshot': 'IC'}
output_times = {'snapshot': a_begin}
initial_conditions = {
    'species': 'matter',
    'N'      : 4**3,
}
" > "${this_dir}/ic.params"
"${concept}" -n 1                       \
             -p "${this_dir}/ic.params" \
             --local
mv "${this_dir}/IC"* "${this_dir}/IC.hdf5"

# Run the CO𝘕CEPT code on the generated ICs
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/params" --local
    mv "${this_dir}/output" "${this_dir}/output_cython_${n}"
done

# Run the CO𝘕CEPT code in pure Python mode on the generated ICs
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/params" --pure-python --local
    mv "${this_dir}/output" "${this_dir}/output_python_${n}"
done

# Tabulate the Ewald grid using pure Python
mv "${reusables_dir}/ewald/${ewald_gridsize}.hdf5" "${this_dir}/ewald_cython.hdf5"
"${concept}" -n 1                                \
             -p "${this_dir}/params_ewald"       \
             -m "import ewald; ewald.tabulate()" \
             --pure-python --local
mv "${reusables_dir}/ewald/${ewald_gridsize}.hdf5" "${this_dir}/ewald_python.hdf5"

# Analyze the output snapshots and Ewald grids
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
