#!/usr/bin/env bash

# This script runs the same, random initial conditions in both compiled
# and pure Python mode and compares the results. The PM algorithm is used.

# Number of processes to use
nprocs_list=(1 2 4)

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Generate ICs
echo "$(cat "${this_dir}/params")
output_dirs  = {'snapshot': '${this_dir}'}
output_bases = {'snapshot': 'IC'}
output_times = {'snapshot': a_begin}
initial_conditions = {
    'species': 'matter',
    'N'      : 8**3,
}
" > "${this_dir}/ic.params"
"${concept}" -n 1                       \
             -p "${this_dir}/ic.params" \
             --local
mv "${this_dir}/IC"* "${this_dir}/IC.hdf5"

# Run the CO𝘕CEPT code on the generated ICs
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/params" --local
    mv "${this_dir}/output" "${this_dir}/output_cython_${n}"
done

# Run the CO𝘕CEPT code in pure Python mode on the generated ICs
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/params" --pure-python --local
    mv "${this_dir}/output" "${this_dir}/output_python_${n}"
done

# Analyse the output snapshots
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
