#!/usr/bin/env bash

# This script performs a drift test of the CO𝘕CEPT code by comparison with
# GADGET-2. Initial conditions are generated, containing 4 particles placed
# symmetrically in the yz-plane so that no net forces exist (due to mirror
# images). An initial velocity in the x-direction is given. The particles will
# pass through the periodic edge of the box during the simulation.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "$(dirname "${this_dir}")")"

# Set up error trapping
ctrl_c() {
    trap : 0
    exit 2
}
abort() {
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Generate initial conditions
"${concept}" -n 1              \
    -p "${this_dir}/param"     \
    -m "${this_dir}/gen_ic.py" \
    --pure-python

# Run the CO𝘕CEPT code on the generated initial conditions
"${concept}"               \
    -n 1                   \
    -p "${this_dir}/param"

# Run the GADGET-2 code on the generated initial conditions
Gadget2_local_dir="${this_dir}/Gadget2"
mkdir -p "${Gadget2_local_dir}"
cp "${Gadget2_dir}/"* "${Gadget2_local_dir}" 2>/dev/null || :
"${concept}" -u gadget "${Gadget2_local_dir}" -p "${this_dir}/param"
(                                        \
    cd "${Gadget2_local_dir}"            \
    && make clean                        \
    && make                              \
    && "${mpiexec}" -n 1 ./Gadget2 param \
)

# Analyse the output snapshots
"${concept}" -n 1               \
    -p "${this_dir}/param"      \
    -m "${this_dir}/analyze.py" \
    --pure-python

# Test ran successfully. Deactivate traps.
trap : 0
