#!/bin/bash

# This script manages the git folder. Execute it to do a forced commit of the Nbody
# directory to the github.com/jmd-dk/Nbody repository, overwrting the existing content.

# cd into the directory of this file
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${this_dir}

# Remove previous content
rm -rf source Nbody_installer

# Copy every file from the Nbody directory into a source subdirectory
source="source"
mkdir ${source}
cp -r ../Nbody/* ${source}

# Also copies the installation script
cp ../Nbody_installer .

# Do cleanup before comitting
cd ${source}
make distclean > /dev/null
cd ..

# Do the commit. Note that this will overwrite the existing master branch!
git init
git remote add origin https://github.com/jmd-dk/Nbody
git add -A
git rm --cached ${this_file}
git commit -m "Comitted from $(dirname ${this_dir})"
git push -f origin master

# Remove created content
rm -rf source Nbody_installer
