#!/usr/bin/env bash

# This script performs a kick test of the CO𝘕CEPT (PP) code, by comparison
# with GADGET-2 (TreePM). ICs are generated, containing 8 particles placed
# symetrically  so that a force only exist in the x-direction. The particles
# start out with zero velocity.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Generate ICs
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/generate_IC.py" --pure-python --local

# Run the CO𝘕CEPT code on the generated ICs
"${concept}" -n 1 -p "${this_dir}/params" --local

# Run the GADGET code on the generated ICs
Gadget2_local_dir="${this_dir}/Gadget2"
mkdir -p "${Gadget2_local_dir}"
cp "${Gadget2_dir}/"* "${Gadget2_local_dir}" 2>/dev/null || :
rm -f "${Gadget2_dir}/ewald_spc_table_64.dat"  # Remove tabulated Ewald grid
"${concept}" -u gadget "${Gadget2_local_dir}" -p "${this_dir}/params"
(                             \
    cd "${Gadget2_local_dir}" \
    && make clean             \
    && make                   \
    && ./Gadget2 params       \
)

# Analyze the output snapshots
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Copy the tabulated Ewald corrections to the Gadget2 directory if it does not
# already exist there, to save time later.
if    [ ! -f "${Gadget2_dir}/ewald_spc_table_64.dat"       ] \
   && [   -f "${Gadget2_local_dir}/ewald_spc_table_64.dat" ]; then
    cp "${Gadget2_local_dir}/ewald_spc_table_64.dat" "${Gadget2_dir}/ewald_spc_table_64.dat"
fi

# Test ran successfully. Deactivate traps.
trap : 0
