#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf IC.hdf5    \
                            ic.params  \
                            output     \
                            output_1   \
                            output_2   \
                            output_4   \
                            output_8   \
                            result.png \
 )
