#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015-2016 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#me $
# The auther of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This utility prints out information about snapshots.
# More specifically, it prints the meta data contained in the snapshot
# (everything except the actual component data).
# You can run this file directly as
# utilities/info path [--generate-params [paramsdir]]
# or invoke it via the concept script as
# ./concept --util info path [--generate-params [paramsdir]]
# In both cases, path is the path to a snapshot file
# or a directory containing snapshot files.
# When the --generate-params flag is set, only the global
# parameters which goes into a parameter file will be printed,
# and in a format understandable by CO𝘕CEPT.



# Absolute paths to this file and its directory
this_file="$(readlink -f "${BASH_SOURCE[0]}")"
this_dir="$(dirname "${this_file}")"

# Source the concept script
source "${this_dir}/../concept"

# Set up error trapping
ctrl_c()
{
    trap : 0
    exit 2
}
abort()
{
    colorprint "An error occurred while using the \"$(basename "${this_file}")\" utility!" "red"
    exit 1
}
if [ "${called_from_concept}" == "True" ]; then
    trap 'ctrl_c' SIGINT
    trap 'abort' EXIT
    set -e
fi

# Use Python's argparse module to handle command-line arguments
args=$("${python}" -c "
import argparse, sys
# Setup command-line arguments
parser = argparse.ArgumentParser(prog='$(basename "${this_file}")',
                                 description='Run the CO𝘕CEPT $(basename "${this_file}") utility')
parser.add_argument('path',
                    help='path to snapshot or directory of snapshots',
                    )
parser.add_argument('-g', '--generate-params',
                    nargs='?',
                    help=('generate parameter file(s) from snapshot(s). Where to save '
                          'the parameter file(s) can be specified as the second argument'),
                    const='${params_dir}',
                    default=False,
                    )
# Enables Python to write directly to screen (stderr)
# in case of help request.
stdout_copy = sys.stdout
sys.stdout = sys.stderr
# Now do the actual argument parsing,
# including writing out the help message.
if '${called_from_concept}' == 'True':
    # Called from concept - Through exception on illegal args
    args = parser.parse_args()
else:
    # Called directly - Allow what appears to be illegal args
    # (these might be known to the concept script).
    args, unknown_args = parser.parse_known_args()
# Reset stdout
sys.stdout = stdout_copy
# Print out the arguments.
# These will be captured in the Bash 'args' variable.
print('argparse_finished=yes'                           + ';',
      'path=\"{}\"'.format(args.path)                   + ';',
      'generate_params={}'.format(args.generate_params) + ';',
      )
" "$@" || :)
# Evaluate the handled arguments into this scope
eval "${args}"
# Exit if argparse exited without finishing
if [ "${argparse_finished}" != "yes" ]; then
    trap : 0
    exit 0
fi

# If not called indirectly through the concept script,
# call the concept script now.
if [ "${called_from_concept}" != "True" ]; then
    "${concept}" --util "${this_file}" "$@"
    trap : 0
    exit 0
fi

# If no parameterfile is supplied,
# use the one that goes along with this utility.
if [ "${params}" == "None" ]; then
    params="${this_file}.params"
fi

# Convert to absolute path
path="$(absolute_path "${path}" "${workdir}")"

# If supplied, convert parameter directory to absolute path
# and put it in quotes. 
if [ "${generate_params}" != "False" ]; then
    generate_params="\'$(absolute_path "${generate_params}" "${workdir}")\'"
fi

# Make temporary parameter file with every information needed
mkdir -p "${this_dir}/params"
params_filename="${this_dir}/params/$(basename "${this_file}").params"
printf "special_params = {
    'special'        : '$(basename "${this_file}")',
    'generate params': ${generate_params},
    'path'           : '${path}',
                  }
$(cat "${params}")
" > "${params_filename}"

# Run CO𝘕CEPT to printout the snapshot information.
# Always run locally using 1 process.
"${concept}" -m "${main}"                  \
             -n 1                          \
             -p "${params_filename}"       \
             --local                       \
             ${pure_python_flag}

# Cleanup
rm -f "${params_filename}"

# Exit gracefully
colorprint "$(basename "${this_file}") utility ran successfully" "green"
trap : 0

