#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015–2021 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see https://www.gnu.org/licenses/
#
# The author of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This utility can produce 3D renders of snapshots.
# You can run this file directly as
# utilities/render3D paths
# or invoke it via the concept script as
# ./concept -u render3D paths
# In both cases, paths are paths to snapshot files
# or a directories containing snapshot files.



# Absolute paths to this file and its directory
this_file="$(readlink -f "${BASH_SOURCE[0]}")"
this_dir="$(dirname "${this_file}")"

# Source the concept script
source "${this_dir}/../concept"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred while using the \"$(basename "${this_file}")\" utility!" "red"
    exit ${exit_code}
}
if [ "${called_from_concept}" == "True" ]; then
    trap 'ctrl_c' SIGINT
    trap 'abort' EXIT
    set -e
fi

# Use Python's argparse module to handle command-line arguments
argparse_finished="False"
argparse_exit_code=""
args=$("${python}" -B -c "
import argparse, sys
# Setup command-line arguments
parser = argparse.ArgumentParser(
    prog='$(basename "${this_file}")',
    description='Run the ${esc_concept} $(basename "${this_file}") utility',
)
parser.add_argument('paths',
                    nargs='+',
                    help='paths to snapshots or directories of snapshots',
                    )
# Enables Python to write directly to screen (stderr)
# in case of help request.
stdout_copy = sys.stdout
sys.stdout = sys.stderr
# Now do the actual argument parsing,
# including writing out the help message.
if '${called_from_concept}' == 'True':
    # Called from concept - Throw exception on illegal args
    args = parser.parse_args()
else:
    # Called directly - Allow what appears to be illegal args
    # (these might be known to the concept script).
    args, unknown_args = parser.parse_known_args()
# Reset stdout
sys.stdout = stdout_copy
# Print out the arguments.
# These will be captured in the Bash 'args' variable.
print('argparse_finished=True')
print('paths=({})'.format(' '.join(['\"{}\"'.format(paths) for paths in args.paths])))
" "$@" || echo "argparse_exit_code=$?")
# Evaluate the handled arguments into this scope
eval "${args}"
# Exit if argparse exited without finishing
if [ "${argparse_finished}" != "True" ]; then
    if [ -z "${argparse_exit_code}" ]; then
        argparse_exit_code=0
    fi
    if [ ${argparse_exit_code} -eq 0 ]; then
        trap : 0
    fi
    exit ${argparse_exit_code}
fi

# If not called indirectly through the concept script,
# call the concept script now.
if [ "${called_from_concept}" != "True" ]; then
    "${concept}" -u="${this_file}" "$@"
    trap : 0
    exit 0
fi

# If no parameter file is supplied,
# use the one that goes along with this utility.
if [ "${params}" == "None" ]; then
    params="${this_file}.params"
fi

# Convert to absolute paths
for i in ${!paths[@]}; do
    paths[${i}]="$(absolute_path "${paths[${i}]}" "${workdir}")"
done

# Get filenames of snapshots and create matching (temporary) parameter files
info="$(                                              \
    "${concept}"                                      \
        -c="${command_line_params}"                   \
        -p="${params}"                                \
        -u=info                                       \
            "$(bash_array2python_list "${paths[@]}")" \
            --generate-params="${this_dir}/params"    \
        ${interactive_flag}                           \
        --local                                       \
        ${native_optimizations_flag}                  \
        ${no_optimizations_flag}                      \
        ${no_recompilation_flag}                      \
        ${pure_python_flag}                           \
        ${unsafe_building_flag}                       \
)"
snapshot_filenames="$(echo "${info}" | grep -x 'Parameters.*' | grep -o '".*"')"
snapshot_params_filenames="$(echo "${info}"                                           \
                             | grep -x 'The above parameters have been written to .*' \
                             | grep -o '".*"')"
snapshot_params_filenames="${snapshot_params_filenames//\"/}"

# Print out the snapshots which will be 3D rendered
N_snapshots="$(echo "${snapshot_filenames}" | wc -l)"
if [ ${N_snapshots} == 1 ]; then
    echo "A 3D render will be produced of the following snapshot:"
else
    echo "3D renders will be produced of the following snapshots:"
fi
echo "${snapshot_filenames}"

# For each snapshot, run the CO𝘕CEPT code to create the 3D render
jobids=()
for ((i = 1; i <= N_snapshots; i += 1)); do
    # Filename of the parameter file to create and use
    params_filename="${this_dir}/params/$(basename "${this_file}").params$((i - 1))"
    # Get the i'th snapshot and generated parameter file
    snapshot_filename="$(echo "${snapshot_filenames}" | sed "${i}q;d")"
    snapshot_params_filename="$(echo "${snapshot_params_filenames}" | sed "${i}q;d")"
    # Make temporary parameter file with everything needed
    echo "
# The special_params dict, specifying details of the utility run
special_params = {
    'special': '$(basename "${this_file}")',
    'snapshot_filename': ${snapshot_filename},
                  }
# Parameter values which should always be used when running this utility
...
# Set the path to the parameter file to be the path to the actual
# parameter file specified by the user, not this auto-generated
# parameter file.
_params_path_ori = paths['params']
paths['params'] = '${params}'
# Auto-generated parameters
$(cat "${snapshot_params_filename}")
###################
# User parameters #
###################
$(cat "${params}")
##########################
# End of user parameters #
##########################
# Reinsert original path to the parameter file
paths['params'] = _params_path_ori
" > "${params_filename}"
    # Cleanup
    rm -f "${snapshot_params_filename}"
    # Run CO𝘕CEPT to produce the 3D render.
    # Submitted jobs should not be watched at this time.
    # Capture the jobid and exit code.
    exec 4>&1
    jobid_and_exit_code="$(                \
        "${concept}"                       \
            -c="${command_line_params}"    \
            -j="${job_directive}"          \
            -m="${main}"                   \
            -n=${nprocs}                   \
            -p="${params_filename}"        \
            -q="${queue}"                  \
            -w="${walltime}"               \
            --memory=${memory}             \
            ${interactive_flag}            \
            ${local_flag}                  \
            ${native_optimizations_flag}   \
            ${no_optimizations_flag}       \
            ${no_recompilation_flag}       \
            --no-watching                  \
            ${pure_python_flag}            \
            ${unsafe_building_flag}        \
        | tee >(cat >&4)                   \
        | grep "^Log file: \|^Job "        \
        | head -n 1                        \
        ; echo "exit_code${PIPESTATUS[0]}" \
    )"
    exec 4>&-
    exit_code="$("${python}" -B -c                                                              \
        "import re; print(re.search(r'exit_code(\d+)', '''${jobid_and_exit_code}''').group(1))" \
        2>/dev/null)" || :
    if [ -z "${exit_code}" ]; then
        colorprint "Error capturing exit code" "red"
        exit 1
    elif [ ${exit_code} != 0 ]; then
        exit ${exit_code}
    fi
    jobid="$("${python}" -B -c                                                                  \
        "import re; print(re.search(r'(/|^Job )(\d+)', '''${jobid_and_exit_code}''').group(2))" \
        2>/dev/null)" || :
    jobids=("${jobids[@]}" "${jobid}")

done

# Deactivate traps before exiting
trap : 0

# Watch remotely submitted jobs in submission order
plural=""
if [ ${N_snapshots} -gt 1 ]; then
    plural="s"
fi
if [ "${remote}" == "True" ] && [ "${no_watching}" == "False" ]; then
    printf "\nYou can now kill (Ctrl+C) this script without cancelling the job${plural}\n"
    printf "\nWill now watch the submitted job${plural}\n\n"
    for jobid in "${jobids[@]}"; do
        "${concept}" -u=watch ${jobid}
        echo
    done
else
    echo
fi

# Exit gracefully
if [ "${remote}" == "False" ] || [ "${no_watching}" == "False" ]; then
    completely_successful="yes"
    for jobid in "${jobids[@]}"; do
        if [ -z "${jobid}" ]; then
            colorprint "Error capturing jobid from output" "red"
            exit 1
        fi
        if [ -f "${logs_dir}/${jobid}_err" ]; then
            completely_successful="no"
        fi
    done
    if [ "${completely_successful}" == "yes" ]; then
        colorprint "$(basename "${this_file}") utility finished successfully" "green"
    else
        echo "$(basename "${this_file}") utility finished"
    fi
else
    echo "$(basename "${this_file}") utility finished. \
Check the submitted job${plural} for results."
fi
