#!/usr/bin/env bash

# This script performs a test of the power spectrum functionality.
# It compares the rms density variation with an estimate obtained by
# taking the rms of cubes the size of spheres with radius
# powerspec_options['tophat']. It also checks the scaling behaviour
# of power spectra (both axes, that is, both k and power) against the
# boxsize and the gridsize of the grid used to compute
# the power spectra.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Generate snapshot
"${concept}" -n 1                                  \
             -p "${this_dir}/params"               \
             -m "${this_dir}/generate_snapshot.py" \
             --pure-python                         \
             --local

# Compute power spectrum of the first snapshot
"${concept}" -n 1 -p "${this_dir}/params" -u powerspec "${this_dir}/snapshot.hdf5" --local

# Compute power spectrum of the snapshot with double the boxsize
cp "${this_dir}/params" "${this_dir}/params_double_boxsize"
sed -i "s/boxsize *=/boxsize = 2*/" "${this_dir}/params_double_boxsize"
"${concept}" -n 1                                                    \
             -p "${this_dir}/params_double_boxsize"                  \
             -u powerspec "${this_dir}/snapshot_double_boxsize.hdf5" \
             --local

# Compute power spectrum of the first snapshot using half the gridsize
mv "${this_dir}/powerspec_snapshot"     "${this_dir}/powerspec_snapshot_original"
mv "${this_dir}/powerspec_snapshot.png" "${this_dir}/powerspec_snapshot_original.png"
cp "${this_dir}/params" "${this_dir}/params_half_gridsize"
sed -i "/_gridsize *=/s/$/\/\/2/" "${this_dir}/params_half_gridsize"
"${concept}" -n 1                                     \
             -p "${this_dir}/params_half_gridsize"    \
             -u powerspec "${this_dir}/snapshot.hdf5" \
             --local
mv "${this_dir}/powerspec_snapshot"     "${this_dir}/powerspec_snapshot_half_gridsize"
mv "${this_dir}/powerspec_snapshot.png" "${this_dir}/powerspec_snapshot_half_gridsize.png"
mv "${this_dir}/powerspec_snapshot_original"     "${this_dir}/powerspec_snapshot"
mv "${this_dir}/powerspec_snapshot_original.png" "${this_dir}/powerspec_snapshot.png"

# Analyze the output snapshots
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
