#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf ic.params        \
                            output_fluid     \
                            output_particles \
                            result.png       \
 )
