#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015–2018 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The author of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This script performs a test of the code's ability to transform
# transfer functions into 3D realizations. Both fluid and particle
# components are tested.

# Number of processes to use
nprocs_list="1 2 4 8"

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Realize matter particles and compute their powerspectrum
for n in ${nprocs_list[@]}; do
    echo "$(cat "${this_dir}/params")
initial_conditions = {
    'name'   : 'test particles',
    'species': 'matter particles',
    'N'      : φ_gridsize**3,
}
output_dirs  = {'powerspec': _this_dir + '/output_particles'}
output_bases = {'powerspec': 'powerspec_nprocs=${n}'}
" > "${this_dir}/ic.params"
    "${concept}" -n ${n}                    \
                 -p "${this_dir}/ic.params" \
                 --local
done

# Realize matter fluid and compute its powerspectrum
for n in ${nprocs_list[@]}; do
    echo "$(cat "${this_dir}/params")
initial_conditions = {
    'name'             : 'test fluid',
    'species'          : 'matter fluid',
    'gridsize'         : φ_gridsize,
    'boltzmann_order'  : 1,
    'boltzmann_closure': 'truncate',
    'approximations'   : {'P=wρ': True},
}
output_dirs  = {'powerspec': _this_dir + '/output_fluid'}
output_bases = {'powerspec': 'powerspec_nprocs=${n}'}
" > "${this_dir}/ic.params"
    "${concept}" -n ${n}                    \
                 -p "${this_dir}/ic.params" \
                 --local
done

# Analyze the output powerspectra
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
