#!/usr/bin/env bash

# This script performs a test of the code's ability to transform
# transfer functions into 3D realizations. Both fluid and particle
# components are tested.

# Number of processes to use
nprocs_list="1 2 4 8"

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Realize matter particles and compute their powerspectrum
for n in ${nprocs_list[@]}; do
    echo "$(cat "${this_dir}/params")
initial_conditions = {
    'name'   : 'test particles',
    'species': 'matter particles',
    'N'      : φ_gridsize**3,
}
output_dirs  = {'powerspec': _this_dir + '/output_particles'}
output_bases = {'powerspec': 'powerspec_nprocs=${n}'}
" > "${this_dir}/ic.params"
    "${concept}" -n ${n}                    \
                 -p "${this_dir}/ic.params" \
                 --local
done

# Realize matter fluid and compute its powerspectrum
for n in ${nprocs_list[@]}; do
    echo "$(cat "${this_dir}/params")
initial_conditions = {
    'name'             : 'test fluid',
    'species'          : 'matter fluid',
    'gridsize'         : φ_gridsize,
    'boltzmann_order'  : 0,
    'boltzmann_closure': 'truncate',
    'approximations'   : {'P=wρ': True},
}
output_dirs  = {'powerspec': _this_dir + '/output_fluid'}
output_bases = {'powerspec': 'powerspec_nprocs=${n}'}
" > "${this_dir}/ic.params"
    "${concept}" -n ${n}                    \
                 -p "${this_dir}/ic.params" \
                 --local
done

# Analyze the output powerspectra
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
