#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf      \
    build_optimized              \
    build_unoptimized            \
    output                       \
    output_optimized             \
    output_unoptimized           \
)
