#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015–2021 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see https://www.gnu.org/licenses/
#
# The author of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This utility will update the CO𝘕CEPT or CLASS source files



# Absolute paths to this file and its directory
this_file="$(readlink -f "${BASH_SOURCE[0]}")"
this_dir="$(dirname "${this_file}")"

# Source the concept script
source "${this_dir}/../concept"

# Set up error trapping
ctrl_c() {
    trap : 0
    exit 2
}
abort() {
    exit_code=$?
    colorprint "An error occurred while using the \"$(basename "${this_file}")\" utility!" "red"
    exit ${exit_code}
}
if [ "${called_from_concept}" == "True" ]; then
    trap 'ctrl_c' SIGINT
    trap 'abort' EXIT
    set -e
fi

# Use Python's argparse module to handle command-line arguments
argparse_finished="False"
argparse_exit_code=""
args=$("${python}" -B -c "
import argparse, sys
# Setup command-line arguments
parser = argparse.ArgumentParser(
    prog='$(basename "${this_file}")',
    description='Run the ${esc_concept} $(basename "${this_file}") utility',
)
parser.add_argument(
    'version',
    help=(
        'version to update to. You may specify a release version '
        '(e.g. \'0.3.0\'), the master version (\'master\'), '
        'a GitHub commit hash '
        '(e.g. \'cf3c210e12527691433f960e7d27249a545fb320\') '
        'or the currently installed version (\'current\').'
    ),
)
parser.add_argument(
    '-y', '--yes-to-defaults',
    default=False,
    action='store_true',
    help=(
        'accept default options on future queries '
        '(passed on to install script)'
    ),
)
parser.add_argument(
    '--class',
    default=False,
    action='store_true',
    help=(
        'update (and patch) CLASS rather than ${esc_concept}. '
        'The version given should still be the ${esc_concept} version.'
    ),
)
# Enables Python to write directly to screen (stderr)
# in case of help request.
stdout_copy = sys.stdout
sys.stdout = sys.stderr
# Now do the actual argument parsing,
# including writing out the help message.
if '${called_from_concept}' == 'True':
    # Called from concept - Throw exception on illegal args
    args = parser.parse_args()
else:
    # Called directly - Allow what appears to be illegal args
    # (these might be known to the concept script).
    args, unknown_args = parser.parse_known_args()
# Reset stdout
sys.stdout = stdout_copy
# Print out the arguments.
# These will be captured in the Bash 'args' variable.
print('argparse_finished=True')
print('version=\"{}\"'.format(args.version))
print('yes_to_defaults=\"{}\"'.format(args.yes_to_defaults))
print('class=\"{}\"'.format(getattr(args, 'class')))
" "$@" || echo "argparse_exit_code=$?")
# Evaluate the handled arguments into this scope
eval "${args}"
# Exit if argparse exited without finishing
if [ "${argparse_finished}" != "True" ]; then
    if [ -z "${argparse_exit_code}" ]; then
        argparse_exit_code=0
    fi
    if [ ${argparse_exit_code} -eq 0 ]; then
        trap : 0
    fi
    exit ${argparse_exit_code}
fi

# If not called indirectly through the concept script,
# call the concept script now.
if [ "${called_from_concept}" != "True" ]; then
    "${concept}" -u="${this_file}" "$@"
    trap : 0
    exit 0
fi

# Borrow some functions from the (current) install script.
# Sourcing is no good here, as we are not interested in
# actually running the install script.
install_functions="               \
    build_sudo_func               \
    check_system_dependency       \
    download                      \
    extract                       \
    set_concept_files             \
    set_package_manager_and_names \
    set_package_names             \
    validate_url                  \
"
function_definitions="$("${python}" -B -c "
import re, sys
with open('${install}', mode='r', encoding='utf-8') as file:
    install_content = file.read()
for install_function in '${install_functions}'.split():
    print(re.search(rf'{install_function}\(\).*?\n}}', install_content, flags=re.DOTALL).group())
" )"
eval "${function_definitions}"

# Create dummy functions called by the borrowed functions
dummy_functions=(    \
    "disable_status" \
    "enable_status"  \
    "error"          \
    "heading"        \
    "set_status"     \
)
for dummy_function in "${dummy_functions[@]}"; do
eval "
${dummy_function}() {
    :
}"
done

# Check for needed system commands
set_package_manager_and_names
check_system_dependency "gzip" "${gzip_package}"
check_system_dependency "tar"  "${tar_package}"
check_system_dependency "wget" "${wget_package}"

# URLs to the CO𝘕CEPT source code and the installation script
if [[ "${version}" == *"."* ]] && [[ "${version}" != "v"* ]]; then
    version="v${version}"
fi
concept_url="https://github.com/jmd-dk/concept/archive/${version}.tar.gz"
install_url="https://raw.githubusercontent.com/jmd-dk/concept/${version}/install"

# Check that the specified version of CO𝘕CEPT exists
if [ "${version}" != "current" ]; then
    validate_url "CONCEPT" "False"
    if [ "${validate_url_status}" != "success" ]; then
        colorprint "Could not find ${esc_concept} version ${version} online. \
Check out https://github.com/jmd-dk/concept/ for available versions." "red"
        exit 1
    fi
fi

# Get and print out update information
current_version="$("${concept}" -v | tail -n 1 || :)"
if [[ "${current_version}" == *"."* ]] && [[ "${current_version}" != "v"* ]]; then
    current_version="v${current_version}"
fi
if [ "${class}" == "False" ]; then
    printf "Update ${esc_concept} \"${current_version}\" → \"${version}\"\n"
else
    # Download the install script from the specified version
    rm -rf "${tmp_dir}/install"
    if [ "${version}" == "current" ]; then
        mkdir -p "${tmp_dir}/install"
        cp "${install}" "${tmp_dir}/install/"
    else
        download "install" "False" "${install_url}" 2>/dev/null
    fi
    # Get and print out CLASS information
    current_class_version="$(                                     \
        (                                                         \
            "${concept}"                                          \
                -m "import linear; print(linear.class__VERSION_)" \
                --pure-python                                     \
                --local                                           \
            2>/dev/null                                           \
            || echo "error"                                       \
        ) | tail -n 1                                             \
    )"
    if [ -z "${current_class_version}" ] || [ "${current_class_version}" == "error" ]; then
        current_class_version="<unknown>"
    fi
    if [ -z "${class_version}" ]; then
        class_version="$(grep "set_version.*class" "${tmp_dir}/install/install" \
            | awk '{print $NF}')"
    fi
    eval "class_version=${class_version}"
    if [[ "${class_version}" == *"."* ]] && [[ "${class_version}" != "v"* ]]; then
        class_version="v${class_version}"
    fi
    export class_version="${class_version}"
    printf "Update CLASS \"${current_class_version}\" (CLASS version) → \
\"${class_version}\" (CLASS version) / \"${version}\" (${esc_concept} version)
"
fi
if [ -z "${sleep_time}" ]; then
    eval "$(grep "sleep_time=" "${install}" | head -n 1)"
fi
sleep ${sleep_time}
export sleep_time=0

# If it is CLASS that is to be updated, do so and exit
backups_dir="${tmp_dir}/backups"
if [ "${class}" == "True" ]; then
    # Backup entire CLASS directory and the classy site-packages files
    mkdir -p "${backups_dir}"
    rm -rf "${backups_dir}/class"
    cp -r "${class_dir}" "${backups_dir}/class" 2>/dev/null || :
    python_version_major_dot_minor="$( \
        "${python}" -c "pass; \
from sys import version_info as v; \
print(str(v.major) + '.' + str(v.minor)); \
")"
    sitepackages_dir="${python_dir}/lib/python${python_version_major_dot_minor}/site-packages"
    rm -rf "${backups_dir}/classy"
    mkdir -p "${backups_dir}/classy"
    cp -r "${sitepackages_dir}/classy"* "${backups_dir}/classy/" 2>/dev/null || :
    # Remove CLASS and classy
    rm -rf "${class_dir}"
    for f in "${sitepackages_dir}/classy"*; do
        rm -rf "${f}" || :
    done
    # Install CLASS
    rm -rf "${tmp_dir}/class"
    class_dir_backup="${class_dir}"
    unset class_dir
    yes_to_defaults_flag=""
    if [ "${yes_to_defaults}" == "True" ]; then
        yes_to_defaults_flag="-y"
    fi
    concept_install="False" class_install="True" python_dir="${python_dir}"                     \
        check_other_running_installation="False" check_preinstalled="False" cleanup_tmp="False" \
        say_welcome="False" say_copyright="False" say_goodbye="False"                           \
        bash "${tmp_dir}/install/install" ${yes_to_defaults_flag} "${concept_dir}" || :
    # Cleanup
    rm -rf "${tmp_dir}/install"
    class_dir="${class_dir_backup}"
    # Test CLASS
    if [ -d "${blas_dir}" ]; then
        export LD_LIBRARY_PATH="${blas_dir}/lib:${LD_LIBRARY_PATH}"
    fi
    test_success="True"
    if ! "${python}" -B -c "
import sys
from classy import Class
cosmo = Class()
cosmo.compute()
sys.exit(int(cosmo.get_background()['proper time [Gyr]'][-1]) != 13)
" 2>/dev/null; then
        test_success="False"
    fi
    # Exit on failure
    if [ "${test_success}" == "False" ]; then
        # Reinsert and remove the CLASS and classy backups before exiting
        rm -rf "${class_dir}"
        cp -r "${backups_dir}/class" "${class_dir}" 2>/dev/null || :
        rm -rf "${backups_dir}/class"
        cp -r "${backups_dir}/classy/"* "${sitepackages_dir}/" 2>/dev/null || :
        rm -rf "${backups_dir}/classy"
        if [ -d "${backups_dir}" ] && [ -z "$(ls -A "${backups_dir}")" ]; then
            rm -rf "${backups_dir}"
        fi
        # Recursively cleanup tmp directory
        cleanup_empty_tmp
        colorprint "The updated CLASS did not function correctly. \
The update has been undone." "red"
        exit 1
    fi
    # Write out success message
    printf "
CLASS \"${class_version}\" (CLASS version) / \"${version}\" (${esc_concept} version) installed
"
    if [ -d "${backups_dir}" ]; then
        printf "
A backup of the existing CLASS code has been placed in
\"${backups_dir}/class\"
and
\"${backups_dir}/classy\"
"
    fi
    if [ -d "${reusable_dir}/class" ] && [ -n "$(ls -A "${reusable_dir}/class")" ]; then
        colorprint "\nNote" "yellow"
        printf "You should remove cached CLASS dumps. You can do so by executing
(cd \"${concept_dir}\" && source \"${concept}\" && make clean_class_reusable)\n\n"
    fi
    colorprint "$(basename "${this_file}") utility finished successfully" "green"
    # Exit gracefully
    trap : 0
    exit 0
fi

# These temporary files may be left over from
# previous invocations of this script.
rm -rf "${tmp_dir}/install" "${util_dir}/update_new"

# Download and extract the specified version of CO𝘕CEPT
mkdir -p "${tmp_dir}"
rm -rf "${tmp_dir}/concept"
if [ "${version}" == "current" ]; then
    current_dir="$(pwd)"
    mkdir -p "${tmp_dir}/concept/concept-existing"
    cd "${tmp_dir}/concept"
    set_concept_files
    existing_files=()
    for f in "${files[@]}"; do
        f="${concept_dir}/${f}"
        if [ -f "${f}" ] || [ -d "${f}" ]; then
            cp -r "${f}" "concept-existing/"
        fi
    done
    tar -cf - "concept-existing" | gzip > "concept-existing.tar.gz"
    rm -rf "concept-existing"
    cd "${current_dir}"
else
    download "CONCEPT"
fi
extract "CONCEPT"

# Take backup of all original CO𝘕CEPT files also present in the new version
backup_dir="${backups_dir}/concept"
rm -rf "${backup_dir}"
mkdir -p "${backup_dir}"
new_files=()
take_backup() {
    current_dir="$1"
    for file in "${current_dir}/"*; do
        if [ ! -d "${concept_dir}/${file}" ] && [ ! -f "${concept_dir}/${file}" ]; then
            new_files=("${new_files[@]}" "${file}")
        fi
        if [ -d "${file}" ]; then
            take_backup "${file}"
        elif [ -f "${concept_dir}/${file}" ]; then
            mkdir -p "${backup_dir}/$(dirname "${file}")"
            cp "${concept_dir}/${file}" "${backup_dir}/${file}"
        fi
        current_dir="$1"
    done
}
for file in "${tmp_dir}/concept/"*; do
    if [ -d "${file}" ]; then
        cd "${file}"
        break
    fi
done
take_backup .

# Move the new update utility, as Bash might crash
# if we removed the very script it is executing.
new_update_utility="./util/update"
new_update_utility_moved="${this_file}_new"
if [ -f "${new_update_utility}" ]; then
    mv "${new_update_utility}" "${new_update_utility_moved}"
fi

# Copy new files into the installation directory,
# overwriting all files. We exclude installation specific files.
files_installation_specific=(".env" ".git" ".path")
for f in * .[^.]*; do
    skip="False"
    for f_exclude in "${files_installation_specific[@]}"; do
        if [ "${f}" == "${f_exclude}" ]; then
            skip="True"
            break
        fi
    done
    if [ "${skip}" == "True" ]; then
        continue
    fi
    cp -r "${f}" "${concept_dir}/"
done
# Cleanup
cd "${concept_dir}"
rm -rf "${tmp_dir}/concept"

# Test CO𝘕CEPT
test_success="True"
if ! "${concept}" -c "H0 = 72*km/(s*Mpc)" -m "
from commons import *
h = H0/(100*units.km/(units.s*units.Mpc))
sys.exit(not isclose(h, 0.72))
" --pure-python --local >/dev/null 2>&1; then
    test_success="False"
fi
# Exit on failure
if [ "${test_success}" == "False" ]; then
    # Reinsert and remove the CO𝘕CEPT backup
    # and delete newly introduced files before exiting.
    rm -f "${backup_dir}/util/update"  # no need to overwrite this with itself
    cp -r "${backup_dir}/"* "${concept_dir}/"
    rm -rf "${backup_dir}"
    for file in "${new_files[@]}"; do
        rm -rf "${concept_dir}/${file}" || :
    done
    if [ -d "${backups_dir}" ] && [ -z "$(ls -A "${backups_dir}")" ]; then
        rm -rf "${backups_dir}"
    fi
    # Recursively cleanup tmp directory
    cleanup_empty_tmp
    colorprint "The updated ${esc_concept} did not function correctly. \
The update has been undone." "red"
    exit 1
fi

# Write out success message
printf "
${esc_concept} version \"${version}\" installed
"
if [ -d "${backup_dir}" ]; then
    printf "
A backup of the existing ${esc_concept} source code has been placed in
\"${backup_dir}\"
"
fi
colorprint "$(basename "${this_file}") utility finished successfully" "green"

# For graceful exit
trap : 0

# As the very last thing, overwrite this file
# with its updated version.
if [ -f "${new_update_utility_moved}" ]; then
    mv "${new_update_utility_moved}" "${this_file}"
fi
