#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf          \
    param_specialized                \
    result.png                       \
    t_class=False_compiled=False.dat \
    t_class=False_compiled=True.dat  \
    t_class=True_compiled=False.dat  \
    t_class=True_compiled=True.dat   \
)
