#!/usr/bin/env bash

# This script performs a comparison test of the evolution of
# the scale factor, between the built-in Friedmann equation
# (integrated via Runge-Kutta-Fehlberg) and the tabulated
# and splined values computed by CLASS, in both pure Python
# and compiled mode.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "$(dirname "${this_dir}")")"

# Set up error trapping
ctrl_c() {
    trap : 0
    exit 2
}
abort() {
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Perform pure Python and compiled test with CLASS background disabled
for pure_python in True False; do
    "${concept}"                             \
        -n 1                                 \
        -p "${this_dir}/param"               \
        -c "enable_class_background = False" \
        -m "${this_dir}/analyze.py"          \
        --pure-python=${pure_python}
done

# Perform pure Python and compiled test with CLASS background enabled
for pure_python in True False; do
    "${concept}"                            \
        -n 1                                \
        -p "${this_dir}/param"              \
        -c "enable_class_background = True" \
        -m "${this_dir}/analyze.py"         \
        --pure-python=${pure_python}
done

# Test ran successfully. Deactivate traps.
trap : 0
