#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf output                          \
                            output_big_linear               \
                            output_big_nonlinear            \
                            output_small_massless           \
                            output_small_massive_linear     \
                            output_small_massive_nonlinear  \
                            params_big_linear               \
                            params_big_nonlinear            \
                            params_small_massless           \
                            params_small_massive_linear     \
                            params_small_massive_nonlinear  \
                            result_abs.png                  \
                            result_rel.png                  \
 )
