#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015–2018 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The author of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This script performs CO𝘕CEPT runs with matter particles
# and a massive neutrino fluid, the latter of which is threated
# both linerly and non-linearly.
# The absolute non-linear neutrino power spectrum is matched
# against the linear solution at large scales, while the relative
# total power spectrum (relative to a cosmology with a
# massless neutrino) is matched against the behaviour
# found in https://arxiv.org/pdf/0802.3700.pdf .

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Function that runs the ${sim} CO𝘕CEPT simulation
# and also generates N-body gauge CLASS results
# using the CLASS utility.
run_concept(){
    also_run_class_util="$1"
    mkdir "${this_dir}/output"
    # Run the ClASS utility
    if [ "${also_run_class_util}" == "yes" ]; then
        echo "
# This ensures that the CLASS run will be reused afterwards
# when running a normal simulation.
try:
    special_params['keep_class_extra_background'] = False
except:
    pass
" >> "${this_dir}/params_${sim}"
        "${concept}"                       \
            -n 4                           \
            -p "${this_dir}/params_${sim}" \
            --local                        \
            -u CLASS                       \
                --max_a_values=1000        \
                --gauge=N-body
    fi
    # Run CO𝘕CEPT
    "${concept}"                       \
        -n 4                           \
        -p "${this_dir}/params_${sim}" \
        --local
    mv "${this_dir}/output" "${this_dir}/output_${sim}"
}



#################################################
# Absolute neutrino power spectra, large scales #
#################################################
# Run the non-linear neutrino simulation
sim="big_nonlinear"
cp "${this_dir}/params" "${this_dir}/params_${sim}"
echo "
initial_conditions.append({
    'name'             : 'neutrino',
    'species'          : 'neutrino fluid',
    'gridsize'         : _size,
    'boltzmann_order'  : 2,
    'boltzmann_closure': 'class',
})
" >> "${this_dir}/params_${sim}"
run_concept "no"

# Run the linear neutrino simulation
sim="big_linear"
cp "${this_dir}/params" "${this_dir}/params_${sim}"
echo "
initial_conditions.append({
    'name'             : 'neutrino',
    'species'          : 'neutrino fluid',
    'gridsize'         : _size,
    'boltzmann_order'  : 0,
    'boltzmann_closure': 'class',
})
" >> "${this_dir}/params_${sim}"
run_concept "no"




##############################################
# Relative total power spectra, small scales #
##############################################
boxsize_small="256*Mpc"
# Run the massless neutrino simulation
sim="small_massless"
cp "${this_dir}/params" "${this_dir}/params_${sim}"
echo "
boxsize = ${boxsize_small}
class_params['m_ncdm'] = 1e-100
" >> "${this_dir}/params_${sim}"
run_concept "yes"

# Run the non-linear massive neutrino simulation
sim="small_massive_nonlinear"
cp "${this_dir}/params" "${this_dir}/params_${sim}"
echo "
boxsize = ${boxsize_small}
initial_conditions.append({
    'name'             : 'neutrino',
    'species'          : 'neutrino fluid',
    'gridsize'         : _size,
    'boltzmann_order'  : 2,
    'boltzmann_closure': 'class',
})
" >> "${this_dir}/params_${sim}"
run_concept "no"

# Run the linear massive neutrino simulation
sim="small_massive_linear"
cp "${this_dir}/params" "${this_dir}/params_${sim}"
echo "
boxsize = ${boxsize_small}
initial_conditions.append({
    'name'             : 'neutrino',
    'species'          : 'neutrino fluid',
    'gridsize'         : _size,
    'boltzmann_order'  : 0,
    'boltzmann_closure': 'class',
})
" >> "${this_dir}/params_${sim}"
run_concept "yes"



# Analyze the output snapshots
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
