#!/usr/bin/env bash

# This script performs a comparison test between the fluid
# and the particle implementation. Random initial conditions
# are generated. The comparison is performed on the large-scale
# part of the power spectra, and also on the position and size
# of the largest halo.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c() {
    trap : 0
    exit 2
}
abort() {
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Generate initial conditions
echo "$(cat "${this_dir}/param")
output_dirs  = {'snapshot': '${this_dir}'}
output_bases = {'snapshot': 'ic'}
output_times = {'snapshot': a_begin}
initial_conditions = {
    'name'   : 'test particles',
    'species': 'matter',
    'N'      : _size**3,
}
" > "${this_dir}/ic.param"
"${concept}" -n 1                      \
             -p "${this_dir}/ic.param" \
             --local
mv "${this_dir}/ic_"* "${this_dir}/ic.hdf5"

# Run the CO𝘕CEPT code on the particle initial conditions
"${concept}" -n 1 -p "${this_dir}/param" --local
mv "${this_dir}/output" "${this_dir}/output_particles"

# Function for converting particle snapshots to fluid snapshots
gridsize=$(get_param "_size")
particles2fluid() {
    "${concept}" --local -u convert "${1}"       \
        "test particles.gridsize = ${gridsize}"  \
        "test particles.name     = test fluid"
}

# Convert the particle initial conditions to fluid initial conditions
particles2fluid "${this_dir}/ic.hdf5"
mv "${this_dir}/ic.hdf5" "${this_dir}/ic_particles.hdf5"
mv "${this_dir}/ic_converted.hdf5" "${this_dir}/ic.hdf5"

# Run the CO𝘕CEPT code on the fluid initial conditions
"${concept}" -n 1 -p "${this_dir}/param" --local
mv "${this_dir}/ic.hdf5" "${this_dir}/ic_fluid.hdf5"
mv "${this_dir}/output" "${this_dir}/output_fluid"

# Convert the particle snapshots to the fluid representation
particles2fluid "${this_dir}/output_particles"

# Analyse the output snapshots
"${concept}" -n 1 -p "${this_dir}/param" -m "${this_dir}/analyze.py" \
    --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
