#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf \
    ic.hdf5                 \
    ic.param                \
    output                  \
    output_1                \
    output_2                \
    output_4                \
    output_8                \
    result.png              \
)
