#!/usr/bin/env bash

# This script runs the same, random initial conditions with different numbers
# of processes and compares the result. The PM algorithm is used.

# Number of processes to use
nprocs_list=(1 2 4 8)

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "$(dirname "${this_dir}")")"

# Set up error trapping
ctrl_c() {
    trap : 0
    exit 2
}
abort() {
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Generate initial conditions
echo "$(cat "${this_dir}/param")
output_dirs  = {'snapshot': '${this_dir}'}
output_bases = {'snapshot': 'ic'}
output_times = {'snapshot': a_begin}
initial_conditions = {
    'species': 'matter',
    'N'      : 8**3,
}
" > "${this_dir}/ic.param"
"${concept}" -n 1                      \
             -p "${this_dir}/ic.param" \
             --local
mv "${this_dir}/ic_"* "${this_dir}/ic.hdf5"

# Run the CO𝘕CEPT code on the generated initial conditions
for n in ${nprocs_list[@]}; do
    "${concept}" -n ${n} -p "${this_dir}/param" --local
    mv "${this_dir}/output" "${this_dir}/output_${n}"
done

# Analyse the output snapshots
"${concept}" -n 1 -p "${this_dir}/param" -m "${this_dir}/analyze.py" \
    --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
