#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf IC.hdf5           \
                            IC_fluid.hdf5     \
                            IC_particles.hdf5 \
                            ic.params         \
                            output            \
                            output_fluid      \
                            output_particles  \
 )
