#!/usr/bin/env bash

# This script performs a comparison test between the fluid
# and the particle implementation. Random initial conditions
# are generated. The comparison is performed on the large-scale
# part of the power spectra, and also on the position and size
# of the largest halo.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Generate ICs
echo "$(cat "${this_dir}/params")
output_dirs  = {'snapshot': '${this_dir}'}
output_bases = {'snapshot': 'IC'}
output_times = {'snapshot': a_begin}
initial_conditions = {
    'name'   : 'test particles',
    'species': 'matter',
    'N'      : _size**3,
}
" > "${this_dir}/ic.params"
"${concept}" -n 1                       \
             -p "${this_dir}/ic.params" \
             --local
mv "${this_dir}/IC"* "${this_dir}/IC.hdf5"

# Run the CO𝘕CEPT code on the particle ICs
"${concept}" -n 1 -p "${this_dir}/params" --local
mv "${this_dir}/output" "${this_dir}/output_particles"

# Function for converting particle snapshots to fluid snapshots
gridsize=$(get_param "_size")
particles2fluid(){
    "${concept}" --local -u convert "${1}"       \
        "test particles.gridsize = ${gridsize}"  \
        "test particles.name     = test fluid"
}

# Convert the particle ICs to fluid ICs
particles2fluid "${this_dir}/IC.hdf5"
mv "${this_dir}/IC.hdf5" "${this_dir}/IC_particles.hdf5"
mv "${this_dir}/IC_converted.hdf5" "${this_dir}/IC.hdf5"

# Run the CO𝘕CEPT code on the fluid ICs
"${concept}" -n 1 -p "${this_dir}/params" --local
mv "${this_dir}/IC.hdf5" "${this_dir}/IC_fluid.hdf5"
mv "${this_dir}/output" "${this_dir}/output_fluid"

# Convert the particle snapshots to the fluid representation
particles2fluid "${this_dir}/output_particles"

# Analyse the output snapshots
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
