#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015–2018 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The author of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This script performs a comparison test between the fluid
# and the particle implementation. Random initial conditions
# are generated. The comparison is performed on the large-scale
# part of the power spectra, and also on the position and size
# of the largest halo.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c()
{
    trap : 0
    exit 2
}
abort()
{
    colorprint "An error occurred during ${this_test} test!" "red"
    exit 1
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Generate ICs
echo "$(cat "${this_dir}/params")
output_dirs  = {'snapshot': '${this_dir}'}
output_bases = {'snapshot': 'IC'}
output_times = {'snapshot': a_begin}
initial_conditions = {'name'   : 'test particles',
                      'species': 'matter particles',
                      'N'      : φ_gridsize**3,
                      }
" > "${this_dir}/ic.params"
"${concept}" -n 1                       \
             -p "${this_dir}/ic.params" \
             --local
mv "${this_dir}/IC"* "${this_dir}/IC.hdf5"

# Run the CO𝘕CEPT code on the particle ICs
"${concept}" -n 1 -p "${this_dir}/params" --local
mv "${this_dir}/output" "${this_dir}/output_particles"

# Function for converting particle snapshots to fluid snapshots
gridsize=$(get_param "φ_gridsize")
particles2fluid()
{
    "${concept}" --local -u convert "${1}"       \
        "test particles.species  = matter fluid" \
        "test particles.gridsize = ${gridsize}"  \
        "test particles.name     = test fluid"
}

# Convert the particle ICs to fluid ICs
particles2fluid "${this_dir}/IC.hdf5"
mv "${this_dir}/IC.hdf5" "${this_dir}/IC_particles.hdf5"
mv "${this_dir}/IC_converted.hdf5" "${this_dir}/IC.hdf5"

# Run the CO𝘕CEPT code on the fluid ICs
"${concept}" -n 1 -p "${this_dir}/params" --local
mv "${this_dir}/IC.hdf5" "${this_dir}/IC_fluid.hdf5"
mv "${this_dir}/output" "${this_dir}/output_fluid"

# Convert the particle snapshots to the fluid representation
particles2fluid "${this_dir}/output_particles"

# Analyze the output snapshots
"${concept}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python --local

# Test ran successfully. Deactivate traps.
trap : 0
