#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf \
    Gadget2                 \
    ic                      \
    output                  \
    result.png              \
)
