#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf \
    ic.param                \
    output                  \
    render3D.param_0        \
    render3D.param_1        \
)
