#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015-2016 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The auther of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This script performs a basic test of the CO𝘕CEPT code.
# It runs the code with no parameter file in both pure Python
# and compiled mode.

# Initialize test environment
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source "${this_dir}/../environment"

# Clean and run in pure Python with different number of cpus
(cd "${concept_dir}" && make clean)
"${concept}"      --pure-python --local
"${concept}" -n 1 --pure-python --local
"${concept}" -n 2 --pure-python --local
"${concept}" -n 4 --pure-python --local

# Build and run in compiled mode with different number of cpus
"${concept}"      --local
"${concept}" -n 1 --local
"${concept}" -n 2 --local
"${concept}" -n 4 --local

# Finalize test environment
test_done=true source "${this_dir}/../environment"

