#!/bin/bash

# This script performs a drift test of the CONCEPT code by comparison with
# GADGET. ICs are generated, containing 4 particles placed symmetrically
# in the yz-plane so that no net forces exist (due to mirror images). A
# initial velocity in the x-direction is given. The particles will pass
# through the periodic edge of the box during the simulation.

# The name of this test (the directory name)
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
test_name=$(basename "${this_dir}")

# Set up error trapping
ctrl_c()
{
    trap : 0
    exit 2
}
abort()
{
    printf "\e[1m\e[91mAn error occurred during ${test_name} test!\e[0m\n" >&2
    exit 1
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Load paths from the .paths file
curr="${this_dir}"
while [ 1 ]; do
    if [ -f "${curr}/.paths" ]; then
        source "${curr}/.paths"
        break
    fi
    if [ "${curr}" == "/" ]; then
        exit 1
    fi
    curr="`dirname \"${curr}\"`"
done

# Create list of output times, used by both CONCEPT and GADGET
"${python}" -c "import numpy as np; np.savetxt('${this_dir}' + '/outputlist', np.linspace(0.03, 1, 2))"

# Generate ICs
"${run}" -n 1 -p "${this_dir}/params" -m "${this_dir}/generate_IC.py" --pure-python --local

# Run the CONCEPT code on the generated ICs
"${run}" -n 1 -p "${this_dir}/params" --local
rm -rf "${this_dir}/output_1"
mv "${this_dir}/output" "${this_dir}/output_1"
"${run}" -n 2 -p "${this_dir}/params" --local
rm -rf "${this_dir}/output_2"
mv "${this_dir}/output" "${this_dir}/output_2"
"${run}" -n 4 -p "${this_dir}/params" --local
rm -rf "${this_dir}/output_4"
mv "${this_dir}/output" "${this_dir}/output_4"
"${run}" -n 8 -p "${this_dir}/params" --local
rm -rf "${this_dir}/output_8"
mv "${this_dir}/output" "${this_dir}/output_8"

# Analyze the output snapshots
"${run}" -n 1 -p "${this_dir}/params" -m "${this_dir}/analyze.py" --pure-python

# Test run complete. Deactivate trap before exiting.
trap : 0
printf "\e[1m\e[92m${test_name^} test ran successfully\e[0m\n"

