#!/bin/bash

# This script does the cleanup after a drift test
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${this_dir}"
rm -rf IC output outputlist params_gadget-usedvalues result.pdf
