#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf Gadget2_local             \
                            lcdm_gas                  \
                            lcdm_gas.Makefile_edited  \
                            lcdm_gas.param-usedvalues \
                            lcdm_gas_littleendian.dat \
                            outputs_lcdm_gas.txt      \
 )
