#!/usr/bin/env bash

# Copyright (C) 2015 Jeppe Mosgard Dakin
#
# This file is part of CONCEPT, the cosmological N-body code in Python
#
# CONCEPT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CONCEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.



# This script does cleanup after a test
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
(cd "${this_dir}" && rm -rf Gadget2_local lcdm_gas IC lcdm_gas.Makefile_edited lcdm_gas.param-usedvalues lcdm_gas_littleendian.dat outputs_lcdm_gas.txt)

