#!/usr/bin/env bash

# This script performs a basic test of the GADGET installation by running a
# shortened version of GADGET's lcdm_gas test.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Create an edited version of lcdm_gas.Makefile with correct path information
cp "${this_dir}/lcdm_gas.Makefile" "${this_dir}/lcdm_gas.Makefile_edited"
sed -i "/^ *CC= / s/ [^# ]/ \"${mpicc//\//\\/}\"/" "${this_dir}/lcdm_gas.Makefile_edited"
path="${mpi_includedir}"
sed -i "/^ *MPI_INCL= / s/ [^# ]/ \"-I${path//\//\\/}\"/" "${this_dir}/lcdm_gas.Makefile_edited"
path="${mpi_libdir}"
MPI_LIBS="\"-L${path//\//\\/}\" -Wl,\"-rpath=${path//\//\\/}\" -lmpi"
if [ -d "${mpi_symlinkdir}" ]; then
    MPI_LIBS="${MPI_LIBS} \"-L${mpi_symlinkdir//\//\\/}\" -Wl,\"-rpath=${mpi_symlinkdir//\//\\/}\""
fi
sed -i "/^ *MPI_LIBS= / s/ [^# ]/ ${MPI_LIBS}/" "${this_dir}/lcdm_gas.Makefile_edited"
path="${gsl_dir}/include"
sed -i "/^ *GSL_INCL= / s/ [^# ]/ \"-I${path//\//\\/}\"/" "${this_dir}/lcdm_gas.Makefile_edited"
path="${gsl_dir}/lib"
sed -i "/^ *GSL_LIBS= / s/ [^# ]/ \"-L${path//\//\\/}\" -Wl,\"-rpath=${path//\//\\/}\"/" \
       "${this_dir}/lcdm_gas.Makefile_edited"
path="${fftw_for_gadget_dir}/include"
sed -i "/^ *FFTW_INCL= / s/ [^# ]/ \"-I${path//\//\\/}\"/" "${this_dir}/lcdm_gas.Makefile_edited"
path="${fftw_for_gadget_dir}/lib"
sed -i "/^ *FFTW_LIBS= / s/ [^# ]/ \"-L${path//\//\\/}\" -Wl,\"-rpath=${path//\//\\/}\"/" \
       "${this_dir}/lcdm_gas.Makefile_edited"

# Copy the IC file and outputlist file from the gadget installation
cp "${gadget_dir}/ICs/lcdm_gas_littleendian.dat" \
   "${Gadget2_dir}/parameterfiles/outputs_lcdm_gas.txt" "${this_dir}"

# Make a local copy of the files in the GADGET2 directory and copy the edited Makefile
Gadget2_local_dir="${this_dir}/Gadget2_local"
mkdir "${Gadget2_local_dir}"
cp "${Gadget2_dir}/"* "${Gadget2_local_dir}" || :
cp "${this_dir}/lcdm_gas.Makefile_edited" "${Gadget2_local_dir}/Makefile"

# Build Gadget and run simulation based on the ICs.
# Note that it is crucial to use a relative path to the parameter file
# as the path has a maximum allowed length in GADGET.
mkdir "${this_dir}/lcdm_gas"
(cd "${Gadget2_local_dir}" && make clean \
                           && make       \
                           && "${Gadget2_local_dir}/Gadget2" ../lcdm_gas.param)

# Analyze the output by checking the size of the snapshot
snapshot_size=$(stat --printf="%s" "${this_dir}/lcdm_gas/snapshot_000")
if [ ! -f "${this_dir}/lcdm_gas/snapshot_000" ]; then
    colorprint "The snapshot \"${this_dir}/lcdm_gas/snapshot_000\" was not produced!" "red"
    exit 1
fi
expected_size=2228536  # Expected size of snapshot_000 in bytes
if [ ! ${snapshot_size} -eq ${expected_size} ]; then
    colorprint "The produced snapshot \"${this_dir}/lcdm_gas/snapshot_000\" \
does not have the expected size of ${expected_size} bytes" "red"
    exit 1
fi

# Test ran successfully. Deactivate traps.
trap : 0
