#!/usr/bin/env bash

# This script does cleanup after a test
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
(cd "${this_dir}" && rm -rf \
    ewald_cython.hdf5       \
    ewald_python.hdf5       \
    ic.hdf5                 \
    ic.param                \
    output                  \
    output_cython_1         \
    output_cython_2         \
    output_cython_4         \
    output_python_1         \
    output_python_2         \
    output_python_4         \
    param_ewald             \
    result.png              \
)
