#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015–2018 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The author of CO𝘕CEPT can be contacted at dakin(at)phys.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This script performs a comparison test of the evolution of
# the scale factor, between the built-in Friedmann equation
# (integrated via Runge-Kutta-Fehlberg) and the tabulated
# and splined values computed by CLASS, in both pure Python
# and compiled mode.

# Absolute path and name of the directory of this file
this_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
this_test="$(basename "${this_dir}")"

# Set up error trapping
ctrl_c(){
    trap : 0
    exit 2
}
abort(){
    exit_code=$?
    colorprint "An error occurred during ${this_test} test!" "red"
    exit ${exit_code}
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

# Cleanup from last test run
"${this_dir}/clean"

# Perform pure Python and compiled test with CLASS background disabled
for pure_python_flag in "--pure-python" ""; do
    cp "${this_dir}/params" "${this_dir}/params_specialized"
    echo "enable_class_background = False" >> "${this_dir}/params_specialized"
    echo "_pure_python = \"${pure_python_flag}\"" >> "${this_dir}/params_specialized"
    "${concept}" -n 1                                \
                 -p "${this_dir}/params_specialized" \
                 -m "${this_dir}/analyze.py"         \
                 ${pure_python_flag}                 \
                 --local
done

# Perform pure Python and compiled test with CLASS background enabled
for pure_python_flag in "--pure-python" ""; do
    cp "${this_dir}/params" "${this_dir}/params_specialized"
    echo "enable_class_background = True" >> "${this_dir}/params_specialized"
    echo "_pure_python = \"${pure_python_flag}\"" >> "${this_dir}/params_specialized"
    "${concept}" -n 1                                \
                 -p "${this_dir}/params_specialized" \
                 -m "${this_dir}/analyze.py"         \
                 ${pure_python_flag}                 \
                 --local
done

# Test ran successfully. Deactivate traps.
trap : 0
