# GitHub action testing building of the docs

name: Build docs


on:
  push:
    paths:
    - '.github/workflows/build_docs.yml'
    - 'concept/docs/**'


jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docs
        run: |
          docker run \
          -v ${GITHUB_WORKSPACE}:/github \
          jmddk/concept:master /usr/bin/env bash -c ': \
              && cd / \
              && source ~/.bashrc \
              && rm -rf "${concept_dir}" \
              && cp -r /github/concept "${concept_dir}" \
              && cd "${concept_dir}" \
              && make -j docs \
          '

