# GitHub action for testing the installer

name: Test installer


on:
    push:
        branches:
          - master
        paths:
          - '.github/workflows/test_installer.yml'
          - 'installer'
          - 'Dockerfile'
    pull_request:
        branches:
          - master
        paths:
          - '.github/workflows/test_installer.yml'
          - 'installer'
          - 'Dockerfile'


jobs:
    test_installer:
        name: Test installer
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Install
            run: docker build -t concept .
          - name: Test installation
            run: docker run concept echo hello  # !!! concept -t all

