#!/usr/bin/env bash

# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
# Copyright © 2015 Jeppe Mosgaard Dakin.
#
# CO𝘕CEPT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CO𝘕CEPT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
#
# The auther of CO𝘕CEPT can be contacted at
# jeppe.mosgaard.dakin(at)post.au.dk
# The latest version of CO𝘕CEPT is available at
# https://github.com/jmd-dk/concept/



# This scipt should not be called manually.
# It handles setup and teardown of the test environment used by all tests.
# - To initialize the test environment, source this file.
# - To finalize the test environment, set the test_done environment variable
#   to true and then source this file.
# The initialization consists of sourcing the concept script (which sources the
# .paths file and declares the colorprint function) and setting up error
# trapping.
# The finalization consists of printing a success message and deactivating
# the error trapping.

#################
# Finalize test #
#################
# Print success message, deactivate trap and return to test script
if [ "${test_done}" = true ]; then
    colorprint "${test_name} test ran successfully" "green"
    trap : 0
    return
fi



###################
# Initialize test #
###################
# Source the concept script
curr="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while :; do
    if [ -f "${curr}/concept" ]; then
        source "${curr}/concept"
        break
    elif [ "${curr}" == "/" ]; then
        # Print out error message and exit
        esc="\x1b"
        esc_normal="${esc}[0m"
        esc_bold="${esc}[1m"
        esc_red="${esc}[91m"
        printf "${esc_bold}${esc_red}Could not find the concept script!${esc_normal}\n" >&2
        exit 1
    fi
    curr="$(dirname "${curr}")"
done

# Export the concept_dir.
# Python scripts can now access it by os.environ['concept_dir'].
export concept_dir="${concept_dir}"

# The name of the test (the directory name)
test_name=$(basename "${0%/*}")

# Set up error trapping
ctrl_c()
{
    trap : 0
    exit 2
}
abort()
{
    colorprint "An error occurred during ${test_name} test!" "red"
    exit 1
}
trap 'ctrl_c' SIGINT
trap 'abort' EXIT
set -e

